image:
  repository: ghcr.io/dragonhunter274/snapdock
  tag: latest
  pullPolicy: Always

deviceName: DJFlab

airplay:
  tcpPort: 5000
  udpPortBase: 6001
  udpPortRange: 3

service:
  type: LoadBalancer

ports:
  snapcastCtrl: 1704
  snapcastStream: 1705
  snapweb: 1780
  auxRtp: 5555
  spotifyZc: 34053
